@extends('layouts/admin')

@section('content')

    <h2>{{ $event->name }}</h2>
    <h3>Wachtlijst</h3>

    <p>
        <a class="btn btn-primary" href="{{ action('Admin\WaitingListController@massInvite', [ $event->id ]) }}">
            Meerdere mensen uitnodigen
        </a>
    </p>

    @if(count($waitingList) === 0)
        <p class="alert alert-info">Er staat nog niemand op de wachtlijst.</p>
    @else
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Op wachtlijst sinds</th>
                    <th>Gebruiker</th>
                    <th>Email</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
            @foreach($waitingList as $listItem)
                @php($user = $listItem['user'])
                <tr>
                    <td>{{ $listItem['index'] }}</td>
                    <td>{{ $user->pivot->created_at->format('d/m/Y H:i') }}</td>
                    <td>{{ $user->username }}</td>
                    <td>{{ $user->email }}</td>
                    <td>
                        @if($listItem['attending'])
                            @if($listItem['group'])
                                Geregistreerd met
                                <a href="{{ action('GroupController@show', [ $listItem['group']->id ]) }}">{{ $listItem['group']->name }}</a>.
                            @else
                                Geregistreerd.
                            @endif
                        @elseif($user->pivot->invitation_sent_at)
                            Uitgenodigd {{ \Carbon\Carbon::parse($user->pivot->invitation_sent_at)->format('d/m/Y H:i') }}
                            &mdash;
                            <a href="{{ action('Admin\WaitingListController@invite', [ $event->id, $user->id ]) }}">opnieuw versturen</a>
                        @elseif($user->pivot->access_token)
                            {{-- Token generated by the old copy-paste flow, or a send that failed. --}}
                            Uitnodiging aangemaakt, niet verstuurd
                            &mdash;
                            <a href="{{ action('Admin\WaitingListController@invite', [ $event->id, $user->id ]) }}">versturen</a>
                        @else
                            <a class="btn btn-warning btn-sm"
                               href="{{ action('Admin\WaitingListController@invite', [ $event->id, $user->id ]) }}">
                                Uitnodigen
                            </a>
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif

@endsection
